# Generated by Django 5.1.3 on 2024-12-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheat',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
